---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
spec:
  ports:
    - port: {{ .Values.db.port }}
      targetPort: 5432 
      name: {{ .Values.db.name }}
      protocol: TCP
  selector:
    app: {{ .Values.db.name }}
  clusterIP: None
