---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
spec:
  ports:
    - port: {{ .Values.web.port }}
      targetPort: 8081
      name: {{ .Values.web.name }}
  selector:
    app: web
  type: LoadBalancer
