---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: krendell12/web-app:database1
        ports:
        - containerPort: 5432
          name: db
      imagePullSecrets:
        - name: regcred 
