---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: krendell12/web-app:web1
        ports:
        - containerPort: 80
          name: web
      imagePullSecrets:
        - name: regcred 
