---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: words
  labels:
    app: words
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: words
    spec:
      containers:
      - name: words
        image: krendell12/web-app:words1
        ports:
        - containerPort: 8080
          name: api
      imagePullSecrets:
        - name: regcred 
